# Generated by Django 5.2.10 on 2026-01-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clubleague',
            fields=[
                ('club_league_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('club_league_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'ClubLeague',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clubmatchesregister',
            fields=[
                ('club_match_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('club_local_score', models.IntegerField()),
                ('club_away_score', models.IntegerField()),
                ('result_label', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'ClubMatchesRegister',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('club_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=200)),
                ('club_value', models.IntegerField()),
                ('club_shield', models.BinaryField()),
            ],
            options={
                'db_table': 'Clubs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clubtournamentregister',
            fields=[
                ('club_tourn_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('club_wins', models.IntegerField()),
                ('club_draws', models.IntegerField()),
                ('club_loses', models.IntegerField()),
                ('club_sc_points', models.IntegerField()),
                ('club_ag_points', models.IntegerField()),
                ('club_position', models.IntegerField()),
                ('club_year', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'ClubTournamentRegister',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nationalteams',
            fields=[
                ('team_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100)),
                ('team_type', models.CharField(max_length=2)),
                ('team_flag', models.BinaryField()),
                ('team_shield', models.BinaryField()),
            ],
            options={
                'db_table': 'NationalTeams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Olympicplayers',
            fields=[
                ('ol_player_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ol_player_name', models.CharField(max_length=200)),
                ('ol_player_value', models.IntegerField()),
                ('ol_player_image', models.BinaryField()),
            ],
            options={
                'db_table': 'OlympicPlayers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Playercountry',
            fields=[
                ('ol_country_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ol_country_name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'PlayerCountry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Playersimulationregister',
            fields=[
                ('sim_ol_reg_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ol_player_result', models.DecimalField(decimal_places=3, max_digits=50)),
                ('ol_player_year', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'PlayerSimulationRegister',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Playertournamentregister',
            fields=[
                ('player_tourn_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ol_player_wins', models.IntegerField()),
                ('ol_player_draws', models.IntegerField()),
                ('ol_player_loses', models.IntegerField()),
                ('ol_player_sc_points', models.IntegerField()),
                ('ol_player_ag_points', models.IntegerField()),
                ('ol_player_position', models.IntegerField()),
                ('ol_player_year', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'PlayerTournamentRegister',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Playertournamentsports',
            fields=[
                ('player_trn_sport_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('player_trn_sport_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'PlayerTournamentSports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sportplayer',
            fields=[
                ('pk', models.CompositePrimaryKey('sp_record_id', 'ol_player_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('player_record_value', models.DecimalField(decimal_places=3, max_digits=50)),
                ('player_record_year', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'SportPlayer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sportsnationalteams',
            fields=[
                ('pk', models.CompositePrimaryKey('team_id', 'sp_record_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('team_record_value', models.DecimalField(decimal_places=3, max_digits=50)),
                ('team_record_year', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'SportsNationalTeams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sportsrecords',
            fields=[
                ('sp_record_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sp_record_name', models.CharField(max_length=100)),
                ('sp_record_best', models.DecimalField(decimal_places=3, max_digits=50)),
                ('sp_record_last', models.DecimalField(decimal_places=3, max_digits=50)),
            ],
            options={
                'db_table': 'SportsRecords',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teammatchesregister',
            fields=[
                ('team_match_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('team_local_score', models.IntegerField()),
                ('team_away_score', models.IntegerField()),
                ('result_label', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'TeamMatchesRegister',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teamranks',
            fields=[
                ('pk', models.CompositePrimaryKey('team_id', 'team_sport_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('team_rank', models.IntegerField()),
            ],
            options={
                'db_table': 'TeamRanks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teamregion',
            fields=[
                ('team_region_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('team_region_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'TeamRegion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teamsimulationregister',
            fields=[
                ('sim_tm_reg_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('team_result', models.DecimalField(decimal_places=3, max_digits=50)),
                ('team_year', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'TeamSimulationRegister',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teamsports',
            fields=[
                ('team_sport_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('team_sport_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'TeamSports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teamtournamentregister',
            fields=[
                ('team_tourn_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('team_wins', models.IntegerField()),
                ('team_draws', models.IntegerField()),
                ('team_loses', models.IntegerField()),
                ('team_sc_points', models.IntegerField()),
                ('team_ag_points', models.IntegerField()),
                ('team_position', models.IntegerField()),
                ('team_year', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'TeamTournamentRegister',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tournamentstage',
            fields=[
                ('tourn_stage_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tourn_stage_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'TournamentStage',
                'managed': False,
            },
        ),
    ]
